[package]
name = "minimp3"
version = "0.2.0"
authors = ["germän gômez <germangb42@gmail.com>", "Erin Moon <erin@hashbang.sh>"]
description = "Rust bindings for the minimp3 library."
keywords = ["mp3", "audio", "decoder", "mpeg", "media"]
categories = ["multimedia", "multimedia::audio"]
license = "MIT"
repository = "https://github.com/germangb/minimp3-rs.git"

[dependencies]
slice-deque = "0.1.8"
minimp3-sys = { path = "minimp3-sys" }
